### ISSUE TITLE
⭐ Feature: create menu buttons

### ISSUE THREAD

**Issue by JJunghyunY** [chanheki/42SeoulRunPackageV2#6]
### Context
 - create menu buttons

### Tasks
- [x] Intra42
- [x] Jiphhyeonjeon
- [x] 24Hane
- [x] 80000Coding
- [x] ~~LogoList~~
- [x] About
- [x] Quit

### Files
 - HomeView.swift
 - MenuButtons.swift

**Comment by JJunghyunY** [comment]
공유받은 프로젝트에서 PreviewProvider 작동오류 - active scheme does not build this file
tuist 설정을 통해 해결 가능한지 알아보기

**Comment by chanhihi** [comment]
https://github.com/chanheki/42SeoulRunPackageV2/pull/7

**Comment by chanhihi** [comment]
done
